FROM debian:8

ENV http_proxy=
ENV https_proxy=

# Add group and user first so they are assigned consistently
RUN groupadd cubit -g __GID__ \
    && useradd -u __UID__ -g cubit cubit

RUN mkdir -p \
        /cubit/tools/easybuild.local \
        /cubit/tools/easybuild/build \
        /cubit/tools/easybuild/ebfiles_repo \
        /cubit/tools/easybuild/modules \
        /cubit/tools/easybuild/software

RUN chown cubit:cubit -R /cubit \
        && chmod ug=rwX,a=rX /cubit

VOLUME /cubit/tools/easybuild.local
VOLUME /cubit/tools/easybuild/build
VOLUME /cubit/tools/easybuild/ebfiles_repo
VOLUME /cubit/tools/easybuild/modules
VOLUME /cubit/tools/easybuild/software
