FROM centos:7

ENV http_proxy=
ENV https_proxy=

# Add group and user first so they are assigned consistently
RUN groupadd cubit -g __GID__ \
    && useradd -u __UID__ -g cubit cubit

RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

# Install required packages
RUN yum install -y \
    autoconf \
    automake \
    bzip2 \
    bzip2-devel \
    environment-modules \
    file \
    gawk \
    gcc \
    gcc-c++ \
    git \
    libbz2-devel \
    libdb-devel \
    libibverbs-devel \
    libpng12 \
    libXt-devel \
    libxml2-devel \
    lzo-devel \
    m4 \
    make \
    mlocate \
    ncurses-libs \
    openssl-devel \
    patch \
    perl \
    perl-Data-Dumper \
    perl-List-MoreUtils \
    pth \
    python-devel \
    python-pip \
    sqlite-devel \
    tar \
    tcsh \
    unzip \
    vim-common \
    wget \
    which \
    zip

# Update cubit's .bashrc
RUN echo "typeset -f module > /dev/null" >> /home/cubit/.bashrc && \
        echo "if [ \$? != 0 -a -r /etc/profile.d/modules.sh ]; then" >> /home/cubit/.bashrc && \
        echo "    source /etc/profile.d/modules.sh" >> /home/cubit/.bashrc && \
        echo "fi" >> /home/cubit/.bashrc

RUN echo "module use __prefix__/current/tools/easybuild/modules/all" >> /home/cubit/.bashrc && \
        echo "module load EasyBuild" >> /home/cubit/.bashrc && \
        echo "export PYTHONPATH=\$PYTHONPATH:__prefix__/current/tools/easybuild.local" >> /home/cubit/.bashrc

# Install modern version of setuptools via pip
RUN pip install setuptools==19.4

# Switch to cubit user
USER cubit

# Go to /home/cubit after login
WORKDIR /cubit.env/tools
