FROM centos:7

ENV http_proxy=
ENV https_proxy=

# Add group and user first so they are assigned consistently
RUN groupadd cubit -g __GID__ \
    && useradd -u __UID__ -g cubit cubit

# Install required packages
RUN yum install -y \
    autoconf \
    automake \
    bzip2 \
    bzip2-devel \
    environment-modules \
    file \
    gawk \
    gcc \
    gcc-c++ \
    git \
    libbz2-devel \
    libdb-devel \
    libibverbs-devel \
    libpng12 \
    libXt-devel \
    libxml2-devel \
    lzo-devel \
    m4 \
    make \
    mlocate \
    ncurses-libs \
    openssl-devel \
    patch \
    perl \
    perl-Data-Dumper \
    perl-List-MoreUtils \
    pth \
    python-devel \
    sqlite-devel \
    tar \
    tcsh \
    unzip \
    vim-common \
    wget \
    which \
    zip

# Update cubit's .bashrc
RUN echo "module use /cubit/tools/easybuild/modules/all" >> /home/cubit/.bashrc && \
        echo "module load EasyBuild" >> /home/cubit/.bashrc

# Switch to cubit user
USER cubit

# Go to /home/cubit after login
WORKDIR /home/cubit
