FROM centos:7

ENV http_proxy=
ENV https_proxy=

# Add group and user first so they are assigned consistently
RUN groupadd cubit -g __GID__ \
    && useradd -u __UID__ -g cubit cubit

RUN mkdir -p \
        /cubit/tools

RUN mkdir -p \
        __PREFIX__

RUN chown cubit:cubit -R /cubit \
        && chmod ug=rwX,a=rX /cubit

VOLUME /cubit/tools
